"""Curated irregular verbs (base / past simple / past participle).

Deterministic data: the drill is checked client-side against this list, so it
needs no LLM and never hallucinates.
"""

from __future__ import annotations

from app.schemas.learning import IrregularVerb

IRREGULAR_VERBS: tuple[IrregularVerb, ...] = (
    IrregularVerb(base="begin", past="began", participle="begun"),
    IrregularVerb(base="break", past="broke", participle="broken"),
    IrregularVerb(base="bring", past="brought", participle="brought"),
    IrregularVerb(base="build", past="built", participle="built"),
    IrregularVerb(base="buy", past="bought", participle="bought"),
    IrregularVerb(base="catch", past="caught", participle="caught"),
    IrregularVerb(base="choose", past="chose", participle="chosen"),
    IrregularVerb(base="come", past="came", participle="come"),
    IrregularVerb(base="cost", past="cost", participle="cost"),
    IrregularVerb(base="cut", past="cut", participle="cut"),
    IrregularVerb(base="do", past="did", participle="done"),
    IrregularVerb(base="draw", past="drew", participle="drawn"),
    IrregularVerb(base="drink", past="drank", participle="drunk"),
    IrregularVerb(base="drive", past="drove", participle="driven"),
    IrregularVerb(base="eat", past="ate", participle="eaten"),
    IrregularVerb(base="fall", past="fell", participle="fallen"),
    IrregularVerb(base="feel", past="felt", participle="felt"),
    IrregularVerb(base="fight", past="fought", participle="fought"),
    IrregularVerb(base="find", past="found", participle="found"),
    IrregularVerb(base="fly", past="flew", participle="flown"),
    IrregularVerb(base="forget", past="forgot", participle="forgotten"),
    IrregularVerb(base="forgive", past="forgave", participle="forgiven"),
    IrregularVerb(base="freeze", past="froze", participle="frozen"),
    IrregularVerb(base="get", past="got", participle="got"),
    IrregularVerb(base="give", past="gave", participle="given"),
    IrregularVerb(base="go", past="went", participle="gone"),
    IrregularVerb(base="grow", past="grew", participle="grown"),
    IrregularVerb(base="have", past="had", participle="had"),
    IrregularVerb(base="hear", past="heard", participle="heard"),
    IrregularVerb(base="hide", past="hid", participle="hidden"),
    IrregularVerb(base="hit", past="hit", participle="hit"),
    IrregularVerb(base="hold", past="held", participle="held"),
    IrregularVerb(base="hurt", past="hurt", participle="hurt"),
    IrregularVerb(base="keep", past="kept", participle="kept"),
    IrregularVerb(base="know", past="knew", participle="known"),
    IrregularVerb(base="lead", past="led", participle="led"),
    IrregularVerb(base="leave", past="left", participle="left"),
    IrregularVerb(base="lend", past="lent", participle="lent"),
    IrregularVerb(base="let", past="let", participle="let"),
    IrregularVerb(base="lose", past="lost", participle="lost"),
    IrregularVerb(base="make", past="made", participle="made"),
    IrregularVerb(base="mean", past="meant", participle="meant"),
    IrregularVerb(base="meet", past="met", participle="met"),
    IrregularVerb(base="pay", past="paid", participle="paid"),
    IrregularVerb(base="put", past="put", participle="put"),
    IrregularVerb(base="read", past="read", participle="read"),
    IrregularVerb(base="ride", past="rode", participle="ridden"),
    IrregularVerb(base="ring", past="rang", participle="rung"),
    IrregularVerb(base="rise", past="rose", participle="risen"),
    IrregularVerb(base="run", past="ran", participle="run"),
    IrregularVerb(base="say", past="said", participle="said"),
    IrregularVerb(base="see", past="saw", participle="seen"),
    IrregularVerb(base="sell", past="sold", participle="sold"),
    IrregularVerb(base="send", past="sent", participle="sent"),
    IrregularVerb(base="set", past="set", participle="set"),
    IrregularVerb(base="shake", past="shook", participle="shaken"),
    IrregularVerb(base="shoot", past="shot", participle="shot"),
    IrregularVerb(base="show", past="showed", participle="shown"),
    IrregularVerb(base="shut", past="shut", participle="shut"),
    IrregularVerb(base="sing", past="sang", participle="sung"),
    IrregularVerb(base="sit", past="sat", participle="sat"),
    IrregularVerb(base="sleep", past="slept", participle="slept"),
    IrregularVerb(base="speak", past="spoke", participle="spoken"),
    IrregularVerb(base="spend", past="spent", participle="spent"),
    IrregularVerb(base="stand", past="stood", participle="stood"),
    IrregularVerb(base="steal", past="stole", participle="stolen"),
    IrregularVerb(base="stick", past="stuck", participle="stuck"),
    IrregularVerb(base="swim", past="swam", participle="swum"),
    IrregularVerb(base="take", past="took", participle="taken"),
    IrregularVerb(base="teach", past="taught", participle="taught"),
    IrregularVerb(base="tear", past="tore", participle="torn"),
    IrregularVerb(base="tell", past="told", participle="told"),
    IrregularVerb(base="think", past="thought", participle="thought"),
    IrregularVerb(base="throw", past="threw", participle="thrown"),
    IrregularVerb(base="understand", past="understood", participle="understood"),
    IrregularVerb(base="wake", past="woke", participle="woken"),
    IrregularVerb(base="wear", past="wore", participle="worn"),
    IrregularVerb(base="win", past="won", participle="won"),
    IrregularVerb(base="write", past="wrote", participle="written"),
)


def all_irregular_verbs() -> list[IrregularVerb]:
    return list(IRREGULAR_VERBS)
